spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true

  #modulith:
   # events:
    #  jdbc:
     #   enabled: true